# For tta settings, freeze the bn5 in deeplabv3 to prevent exception
python tta.py \
--name muta_tta_cadis2catinstseg \
--gpu 7 \
--checkpoints_dir storage/checkpoints/tta \
--phase training \
--model muta_source \
--batch_size 1 \
--input_nc 3 \
--output_nc 6 \
--netTask res50 \
--initialization in_model \
--dataset single_domain \
--data_root PATH_TO_YOUR_DATASET \
--shuffle \
--drop_last \
--preprocess rescale \
--load_size 720 405 \
--mapping_file_name mapping_merge_tools \
--save_freq 10 \
--epoch_end 500 \
--lr 1e-5 \
--lr_policy constant \
--validation \
--file_path storage/source_domain/final_net_Task.pth \
--dropout_rates 0.5 \
--dropout_weights 1 \
--ema_freq 1 \
--momentum 0.999 \
--mu_ssl 1 \
--mu_ent 1 \
--mu_con 1 \
--threshold 0.95 \
--tta_steps 10